let result;
try {
    result = x / 10;
} catch (error) {
    console.log(error.message);
}